{% set name = "js-cookie" %}
{% set version = "2.2.0" %}
{% set sha256 = "bad440c8a5beadc1d78d36dc072d37150abcc5a9a4b483d3583565edfe76c2b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/js-cookie/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: npm install -g .

requirements:
  build:
    - nodejs
  
test:
  commands:
    - npm list -g js-cookie
  requires:
    - nodejs
   

about:
  home: https://github.com/js-cookie/js-cookie
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'A simple, lightweight JavaScript API for handling browser cookies'
  description: |
    A simple, lightweight JavaScript API for handling browser cookies  
  doc_url: https://github.com/js-cookie/js-cookie/tree/latest#readme
  dev_url: https://github.com/js-cookie/js-cookie

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
