{% set name = "js-cookie" %}
{% set version = "3.0.0" %}
{% set sha256 = "fed2b9f81516da4a07d717abd89c3e5c522bf4102d6df95fbdf608211a7a4089" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/js-cookie/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: |
    tgz=$(npm pack)
    npm install -g $tgz

requirements:
  build:
    - nodejs

test:
  commands:
    - npm list -g js-cookie
  requires:
    - nodejs


about:
  home: https://github.com/js-cookie/js-cookie
  license: MIT
  license_family: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: A simple, lightweight JavaScript API for handling browser cookies
  description: |
    A simple, lightweight JavaScript API for handling browser cookies  
  doc_url: https://github.com/js-cookie/js-cookie/tree/latest#readme
  dev_url: https://github.com/js-cookie/js-cookie

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
