travis:
  secure:
    BINSTAR_TOKEN: LzFxYTzJ7I9zeqmw0ltrVXg+g8qBOgm1zij286S/UWtPfanFzWKPAXnaxifzBhwPpetyezwpGXwbv7rnBhntONPfe3C6gMCM3LK9KJAs0awaxn4xj1EYBfmYbD4A8IhAKt0vnF51qgcjadoFSvFIi32z/tZLDW934gwYBP4u4nqVkLFpJqRb7k3wGVJSTc2vSTDN8rfv9dSR5vKzDqufGHlmHSTjfzBZX4ZgLnmGKpXdl2P9ca1V/fMgxIsLoIRmlMZtXnMhhFKexswZMVSBA+6qs/Tqf4oVra24H6WtHcaoYOmHEUCGPjXOLq5VuUaxvnfj48ES/Eccdu0crujJVsJRbV03KpzkfTA34MHuDXYVqhnvNLPEkhKtKX0TIqwsfbYkUXzxfD1gFvBGAvpfq+jVypA8i7ROJTWW9yFnbKddhlacCXjfEJlIbcVa4RX6xREDZ+rxJZcxxrQ4YPclt0IZTgpvkkJyY/kaevG5KI1AvKEUjQQ8mgiLDhBouYzMSBocnCCxkTr1qqV3c6+Ev5lpqGZ0p1TKaEhGl0jbKecnCKto1t/5pJVbChPVd2gfkVo98f+mwSVdS+EdpeFGpW7yLuostt3MJ+bPDGNjX98RaU8PifTXF4/9lOZ5TGRE7criGewrYT2RMq8VUQVdW7YWldDPH4RUsCgn7JOLHK0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
