travis:
  secure:
    BINSTAR_TOKEN: lrMH4SExA/wXhoGeBpSdk3G91TF5pgRy/BB/RAzPo8xNW6olYiO+opktPztbVLlacAQeC+AUyHniUOsU/g8N41/O1a5IiMaT1CoIWOejikdQPbI8pBsVES4+2rlDk+oOnLcKci33VIlG9TcvHks7evGsuIesqb6sFdKkcb4xRCp3yXm/MHHx1jtvjEeIjShmEE7Cg6J2D7QMUh8Gw1iItrQzLUHs32Zh+ndibsNEiwFwRKSFxcAvli1GW0WA0qOR2tSwrs8DmSluzTYnnLOOmk+bub+CG3dw/54VAhJAFk4juEYWq1dFPZeuTFlmC7fR+2SCSuvm1XtjXoFl0lF3mrTXfu+E2UfrBSu/Q2UwN5Cbuebo4oT7LrqQlTBQP09HNp79mDFKr6EpaPsumguIUkTIDbOlM3IDJVzigkbKSd8FcPHnYmeKrxpHfIW9ekxkO5WqaD87DyAW00uXFg66Xa4P+U9MWUTECQZt3cB/FC6uDcmw9nKr9pgdlFaJYSwkvUzZqhr4UOAroz47u6/twmmOSSUZcAVLF1MvwZ0Tq8Vgi9DeOmtfHCGKqx6DU9T1LtpOLuUlTKrjJgfHSYeou1YT8mNvfcsu4XN+4yyGxU8djo9e3lWpjOqxkFRfFKlj0uvit3dlT2ZsEq2zkOjvOJ5T+yEyIKvV+WvjnqS7MMI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
